name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: NPM install
      uses: actions/npm@master
      with:
        args: install
    - name: Expo CLI
      uses: expo/expo-github-action@3.0.0
      env:
        EXPO_CLI_USERNAME: ${{ secrets.EXPO_CLI_USERNAME }}
        EXPO_CLI_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}
        EXPO_DEBUG: true
      with:
        args: publish